services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb/data:/data/db
    networks:
      - app-network

  puppeteer_project:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    environment:
      MONGO_URI: mongodb://mongodb:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge